# MidnightQoL – Manifest Generator (PowerShell)
# ================================================
# Scans the MidnightQoL/Sounds/ and MidnightQoL/Images/ folders and
# regenerates SoundsList.lua and ImagesList.lua so the addon picks up
# any new files automatically.
#
# Usage (run from the repo root, i.e. the folder containing MidnightQoL/):
#   .\generate_manifests.ps1
#
# If you get a "running scripts is disabled" error, run this first:
#   Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned

$AddonDir  = Join-Path $PSScriptRoot "MidnightQoL"
$SoundsDir = Join-Path $AddonDir "Sounds"
$ImagesDir = Join-Path $AddonDir "Images"
$SoundsOut = Join-Path $AddonDir "SoundsList.lua"
$ImagesOut = Join-Path $AddonDir "ImagesList.lua"

$SoundExts    = @(".ogg", ".mp3", ".wav")
$ImageExts    = @(".tga", ".blp", ".png")
$ImageExclude = @("minimap_icon")

Write-Host "MidnightQoL - Manifest Generator"
Write-Host "========================================"

if (-not (Test-Path $AddonDir)) {
    Write-Error "Could not find addon directory at '$AddonDir'.`nMake sure you run this script from the repo root."
    exit 1
}

function Write-LuaManifest {
    param([string]$OutPath, [string]$TableName, [string[]]$Stems, [string[]]$Exclude)
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("-- Auto-generated by generate_manifests.ps1  (do not edit by hand)")
    $lines.Add("${TableName} = {")
    $included = 0
    foreach ($stem in $Stems | Sort-Object { $_.ToLower() }) {
        if ($Exclude -contains $stem) { continue }
        $escaped = $stem -replace '\\', '\\' -replace '"', '\"'
        $lines.Add("    `"$escaped`",")
        $included++
    }
    $lines.Add("}")
    [System.IO.File]::WriteAllLines($OutPath, $lines, [System.Text.UTF8Encoding]::new($false))
    return $included
}

Write-Host "Scanning: $SoundsDir"
if (Test-Path $SoundsDir) {
    $soundStems = Get-ChildItem -Path $SoundsDir -File |
        Where-Object { $SoundExts -contains $_.Extension.ToLower() } |
        Select-Object -ExpandProperty BaseName
    $count = Write-LuaManifest -OutPath $SoundsOut -TableName "SoundsList" -Stems $soundStems -Exclude @()
    Write-Host "  Wrote $count sound(s) -> SoundsList.lua"
} else { Write-Warning "Sounds directory not found, skipping." }

Write-Host "Scanning: $ImagesDir"
if (Test-Path $ImagesDir) {
    $imageStems = Get-ChildItem -Path $ImagesDir -File |
        Where-Object { $ImageExts -contains $_.Extension.ToLower() } |
        Select-Object -ExpandProperty BaseName
    $count = Write-LuaManifest -OutPath $ImagesOut -TableName "ImagesList" -Stems $imageStems -Exclude $ImageExclude
    Write-Host "  Wrote $count image(s) -> ImagesList.lua"
} else { Write-Warning "Images directory not found, skipping." }

Write-Host ""
Write-Host "Done! Reload your UI in WoW (/reload) to pick up the changes."
