#!/usr/bin/env python3
"""
MidnightQoL – Manifest Generator
==================================
Scans the MidnightQoL/Sounds/ and MidnightQoL/Images/ folders and
regenerates SoundsList.lua and ImagesList.lua so the addon picks up
any new files automatically.

Usage (run from the repo root, i.e. the folder containing MidnightQoL/):
    python generate_manifests.py

Works on Windows, macOS, and Linux. Requires Python 3.6+, no extra packages.
"""

import os
import sys
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────

ADDON_DIR   = Path(__file__).parent / "MidnightQoL"
SOUNDS_DIR  = ADDON_DIR / "Sounds"
IMAGES_DIR  = ADDON_DIR / "Images"
SOUNDS_OUT  = ADDON_DIR / "SoundsList.lua"
IMAGES_OUT  = ADDON_DIR / "ImagesList.lua"

SOUND_EXTS  = {".ogg", ".mp3", ".wav"}
IMAGE_EXTS  = {".tga", ".blp", ".png"}

# Files to always exclude from the image list (internal-use only)
IMAGE_EXCLUDE = {"minimap_icon"}

# ── Helpers ───────────────────────────────────────────────────────────────────

def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def scan(directory: Path, extensions: set) -> list:
    if not directory.is_dir():
        print(f"  [WARN] Directory not found, skipping: {directory}")
        return []
    return sorted(
        (p.stem for p in directory.iterdir() if p.suffix.lower() in extensions),
        key=lambda s: s.lower()
    )

# ── Generators ────────────────────────────────────────────────────────────────

def write_sounds(stems: list) -> None:
    lines = ["-- Auto-generated by generate_manifests.py  (do not edit by hand)\n",
             "-- To add sounds: drop .ogg files into MidnightQoL/Sounds/ then run:\n",
             "--   python generate_manifests.py\n",
             "SoundsList = {\n"]
    for stem in stems:
        lines.append(f"    {lua_string(stem)},\n")
    lines.append("}\n")
    SOUNDS_OUT.write_text("".join(lines), encoding="utf-8")
    print(f"  Wrote {len(stems)} sound(s) → SoundsList.lua")

def write_images(stems: list) -> None:
    lines = ["-- Auto-generated by generate_manifests.py  (do not edit by hand)\n",
             "-- To add images: drop .tga/.blp/.png files into MidnightQoL/Images/ then run:\n",
             "--   python generate_manifests.py\n",
             "ImagesList = {\n"]
    included = 0
    for stem in stems:
        if stem in IMAGE_EXCLUDE:
            continue
        lines.append(f"    {lua_string(stem)},\n")
        included += 1
    lines.append("}\n")
    IMAGES_OUT.write_text("".join(lines), encoding="utf-8")
    print(f"  Wrote {included} image(s) → ImagesList.lua")

# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print("MidnightQoL – Manifest Generator")
    print("=" * 40)
    if not ADDON_DIR.is_dir():
        sys.exit(
            f"ERROR: Could not find addon directory at '{ADDON_DIR}'.\n"
            "Make sure you run this script from the repo root."
        )
    print(f"Scanning: {SOUNDS_DIR}")
    write_sounds(scan(SOUNDS_DIR, SOUND_EXTS))
    print(f"Scanning: {IMAGES_DIR}")
    write_images(scan(IMAGES_DIR, IMAGE_EXTS))
    print("\nDone! Reload your UI in WoW (/reload) to pick up the changes.")

if __name__ == "__main__":
    main()
