
BuffAlertDB = {
["alsActivityRules"] = {
["254"] = {
["dungeon"] = {
["loadoutID"] = 57760643,
["loadoutName"] = "M+",
},
},
["253"] = {
["dungeon"] = {
["loadoutID"] = 57760643,
["loadoutName"] = "M+",
},
["raid"] = {
["loadoutID"] = 57760643,
["loadoutName"] = "M+",
},
},
["268"] = {
["openworld"] = {
["loadoutID"] = 59766940,
["loadoutName"] = "m+ Shadow Pan",
},
["warmode"] = {
["loadoutID"] = 57972284,
["loadoutName"] = "PVP",
},
["arena"] = {
["loadoutID"] = 57972284,
["loadoutName"] = "PVP",
},
["raid"] = {
["loadoutID"] = 58908947,
["loadoutName"] = "Brewmaster Raid",
},
["dungeon"] = {
["loadoutID"] = 59766940,
["loadoutName"] = "m+ Shadow Pan",
},
["battleground"] = {
["loadoutID"] = 57972284,
["loadoutName"] = "PVP",
},
},
["270"] = {
["dungeon"] = {
["loadoutID"] = 58722257,
["loadoutName"] = "M+ Midnight",
},
["warmode"] = {
["loadoutID"] = 57968457,
["loadoutName"] = "PVP",
},
["openworld"] = {
["loadoutID"] = 58722257,
["loadoutName"] = "M+ Midnight",
},
["arena"] = {
["loadoutID"] = 57968457,
["loadoutName"] = "PVP",
},
["raid"] = {
["loadoutID"] = 58722257,
["loadoutName"] = "M+ Midnight",
},
["battleground"] = {
["loadoutID"] = 57968457,
["loadoutName"] = "PVP",
},
},
},
["petReminderR"] = 1,
["expBarShowRested"] = true,
["autoQuestAccept"] = true,
["repBarBgR"] = 0,
["subBagIconSize"] = 32,
["buffDebuffAlertsEnabled"] = true,
["wowSettings"] = {
["interactKey"] = "F",
["damageMeter"] = "1",
["savedAt"] = "2026-03-19 21:00",
["autoPushSpell"] = "1",
["leftClickInteract"] = "0",
["autoLoot"] = "1",
["cooldownViewer"] = "1",
},
["expBarColorR"] = 0,
["repBarEnabled"] = true,
["brezX"] = 1714.999900817871,
["trackedExternals"] = {
},
["unitFrames"] = {
["targetW"] = 200,
["focusY"] = -280,
["showPlayer"] = true,
["showParty"] = true,
["showTarget"] = true,
["aggroG"] = 0.1,
["playerW"] = 200,
["partyH"] = 44,
["raidH"] = 36,
["petW"] = 120,
["petH"] = 30,
["showHP"] = true,
["enabled"] = true,
["nameFont"] = 11,
["raidSpacingX"] = 2,
["absorbB"] = 1,
["raidX"] = -420,
["petX"] = -300,
["playerH"] = 50,
["absorbG"] = 0.6,
["focusW"] = 180,
["corners"] = {
["TOPLEFT"] = {
["showDur"] = true,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["TOPRIGHT"] = {
["showDur"] = true,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["BOTTOMLEFT"] = {
["showDur"] = false,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["BOTTOMRIGHT"] = {
["showDur"] = false,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
},
["showPet"] = true,
["borderG"] = 0.15,
["partyW"] = 180,
["raidW"] = 80,
["raidY"] = 160,
["aggroB"] = 0.1,
["incomingG"] = 0.9,
["showHPPct"] = true,
["absorbR"] = 0.2,
["bgAlpha"] = 0.85,
["petY"] = -240,
["raidCols"] = 5,
["partySpacingY"] = 4,
["focusX"] = -300,
["borderB"] = 0.15,
["powerH"] = 4,
["borderR"] = 0.15,
["partyY"] = 160,
["hpFont"] = 10,
["partyX"] = -420,
["borderSize"] = 1,
["targetH"] = 50,
["classColorHP"] = true,
["playerX"] = -300,
["showFocus"] = true,
["targetX"] = 300,
["aggroR"] = 1,
["incomingR"] = 0.2,
["showAbsorb"] = true,
["showIncoming"] = true,
["aggroEnabled"] = true,
["showName"] = true,
["playerY"] = -180,
["raidSpacingY"] = 2,
["targetY"] = -180,
["incomingB"] = 0.2,
["showRaid"] = true,
["focusH"] = 40,
},
["repBarPendingB"] = 0,
["minimapAngle"] = -157.0487922664176,
["repBarPendingR"] = 1,
["whisperEnabled"] = true,
["expBarBgA"] = 0.55,
["debugDump"] = {
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Mantle",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 1,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Reflecting Prism",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 2,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Earth-Encrusted Gem",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 3,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Goblin Glider Kit",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 4,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Earth-Encrusted Gem",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 5,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Disarmed Trap",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 6,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Ouroboros Tablet",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 7,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Impossibly Royal Roast",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 8,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Silvermoon Standard",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 9,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Bloom Skewers",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 10,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Impossibly Royal Roast",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 11,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Spellfire Filet",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 12,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Vile Essence",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 13,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Finery Funds",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 14,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "L00T RAID-R Mini",
["isBound"] = "true",
["_bag"] = 0,
["_slot"] = 15,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Royal Roast",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 16,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Fel-Kissed Filet",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 17,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Royal Roast",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 18,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Champion's Bento",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 19,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Felberry Figs",
["isBound"] = "false",
["_bag"] = 0,
["_slot"] = 20,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Spellfire Filet",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 1,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Silvermoon Standard",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 2,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Bloom Skewers",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 3,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "\"Third Wind\" Potion",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 4,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Hearty Fel-Kissed Filet",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 5,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Convincingly Realistic Jumper Cables",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 6,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Auto-Hammer",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 7,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thermal Anvil",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 8,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Deed of Patronage",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 9,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Guardian's Gemstone Loop",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 10,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Holy Retributor's Order",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 11,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Obsidian Goaltending Spire",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 12,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Gar'chak's Mark of Honor",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 13,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Devouring Outrider's Chausses",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 14,
["bindType"] = "2",
},
{
["hasNoValue"] = "true",
["_name"] = "Potent Healing Potion",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 15,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Mask",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 16,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Verdant Tracker's Cuffs",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 17,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Wristwraps",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 18,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Grips",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 19,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Holy Retributor's Order",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 20,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Cord",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 21,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Drum of Renewed Bonds",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 22,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Breeches",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 23,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Cosmic Bell",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 24,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Cloak",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 25,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Gift of Light",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 26,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Cloak of Coordination",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 27,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Amani Heartstring Pendant",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 28,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Dreadful Gilded Gallybux",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 29,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Band",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 30,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Ring",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 31,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Dreadful Silken Offering",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 32,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Echo of L'ura",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 33,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Medallion",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 34,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Mystic Foreboding Beaker",
["isBound"] = "false",
["_bag"] = 1,
["_slot"] = 35,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Pattern: Blessed Pango Charm",
["isBound"] = "true",
["_bag"] = 1,
["_slot"] = 36,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Reinforced Amani Haft",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 1,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Crackling Shard",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 2,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Mark of Honor",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 3,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Latent Arcana",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 4,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Diamondback-Scale Legguards",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 5,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Warcloak of the Butcher",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 6,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Fangs of the Invader",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 7,
["bindType"] = "2",
},
{
["hasNoValue"] = "true",
["_name"] = "Beacon of Hope",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 8,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Magical Mulch",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 9,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Lynxhide Shawl",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 10,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Lexicologist's Vellum",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 11,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Powder Pigment",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 12,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thalassian Songwater",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 13,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thalassian Essence of the Faire",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 14,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Apprentice's Scribbles",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 15,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Argentleaf Pigment",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 16,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Sanguithorn Pigment",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 17,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Artisan's Ledger",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 18,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Earthy Garnish",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 19,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Mana Lily Pigment",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 20,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Codified Azeroot",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 21,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Savory Anomaly",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 22,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Blazing Ink",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 23,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Mote of Light",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 24,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thalassian Lumber",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 25,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Lightweave Cloth",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 26,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Mana Lily",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 27,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Void Violet Dye",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 28,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Vantus Rune: Radiant",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 29,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Tormented Tantalum",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 30,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Choker",
["isBound"] = "true",
["_bag"] = 2,
["_slot"] = 31,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Mote of Pure Void",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 32,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Argentleaf",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 33,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Argentleaf",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 34,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Mote of Wild Magic",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 35,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Zapthrottle Soul Inhaler",
["isBound"] = "false",
["_bag"] = 2,
["_slot"] = 36,
["bindType"] = "3",
},
{
["hasNoValue"] = "false",
["_name"] = "Talisman of the Dragon Hoard",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 1,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Ethereal Essence Sliver",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 2,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Mote of Primal Energy",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 3,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Stormarion Core",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 4,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Aquarius Bloom",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 5,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Gateway Control Shard",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 6,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Azeroot",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 7,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Abundant Beacon",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 8,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Bloom Bauble",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 9,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Petrified Root",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 10,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Tarnished Safebox Key",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 11,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "A Tattered Ball",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 12,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Void-Tainted Remains",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 13,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Sargle's Fortune #2",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 14,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Sturdy Expedition Shovel",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 15,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Azeroot",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 16,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Sanguithorn",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 17,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Sanguithorn",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 18,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Tranquility Bloom",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 19,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Cooking Spirits",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 20,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thalassian Treatise on Herbalism",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 21,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Saltwater Potion",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 22,
["bindType"] = "0",
},
{
["hasNoValue"] = "true",
["_name"] = "Galactic Gladiator's Heraldry",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 23,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Vest",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 24,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Artisan's Consortium Gold Star",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 25,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Void-Touched Augment Rune",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 26,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Shaggy Wyrmleather Leggings",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 27,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Insignia of Alacrity",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 28,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Plans: Obsidian Seared Hexsword",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 29,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Plagued Pike of the Fireflash",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 30,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Silvermoon Parade",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 31,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Fused Vitality",
["isBound"] = "true",
["_bag"] = 3,
["_slot"] = 32,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Dark Gold Dye",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 33,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Peerless Plumage",
["isBound"] = "false",
["_bag"] = 3,
["_slot"] = 34,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Thalassian Treatise on Inscription",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 1,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Preyseeker's Spire",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 2,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Floratender's Crutch",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 3,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Falconer's Cinch",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 4,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Fine Bioluminescent Powder",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 5,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Glowing Gland",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 6,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Bioluminescent Flower Petals",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 7,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Galactic Aspirant's Leather Footpads",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 8,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Sizable Tusk",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 9,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Definitely Not a Rock",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 10,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Mana Lily",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 11,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Threadbare Slippers",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 12,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Rotting Insect Eggs",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 13,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Verminscale Gavel",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 14,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Tarnished Dawnlit Longbow",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 15,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Grim Harvest Gloves",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 16,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Stained Fistguards",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 17,
["bindType"] = "2",
},
{
["hasNoValue"] = "false",
["_name"] = "Polished Purple Pebble",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 18,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Abrasive Sand",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 19,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Digested Human Hand",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 20,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Nightsong Lilac Dye",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 21,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Lucky Loa",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 22,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Cosmic Bell",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 23,
["bindType"] = "1",
},
{
["hasNoValue"] = "false",
["_name"] = "Gore Guppy",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 24,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Broken Wildlife Claw",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 25,
["bindType"] = "0",
},
{
["hasNoValue"] = "false",
["_name"] = "Voidbreaker's Jacket",
["isBound"] = "true",
["_bag"] = 4,
["_slot"] = 30,
["bindType"] = "1",
},
{
["hasNoValue"] = "true",
["_name"] = "Plain Letter",
["isBound"] = "false",
["_bag"] = 4,
["_slot"] = 31,
["bindType"] = "0",
},
},
["keystones"] = {
["announceWinner"] = true,
["tooltipPercent"] = true,
["autoSlot"] = true,
["wheelSpinTime"] = 5,
},
["subBags"] = {
{
["id"] = "494344537_5904",
["name"] = "Consums",
["search"] = "#consumable",
},
{
["id"] = "sb_591694975_5815",
["name"] = "non set gear",
["search"] = "#armor|#weapon",
},
{
["id"] = "sb_497715427_1884",
["name"] = "Quests",
["search"] = "#questitem",
},
{
["id"] = "sb_497745745_1148",
["name"] = "Recipes",
["search"] = "#recipe",
},
{
["id"] = "sb_591650186_1815",
["name"] = "Gear Set Gear",
["search"] = "#armor&^inset|#weapon&inset",
},
{
["id"] = "sb_497759095_2238",
["name"] = "Trash",
["search"] = "^junk",
},
{
["id"] = "sb_497740510_6901",
["name"] = "Crafting",
["search"] = "#reagent",
},
},
["repBarFillR"] = 0.8,
["trackedBuffs"] = {
},
["subBagCollapsed"] = {
["sb_497720643_9501"] = false,
["494327121_1063"] = true,
["__other"] = false,
["494344537_5904"] = false,
["sb_591694975_5815"] = false,
["sb_497715427_1884"] = false,
["sb_497745745_1148"] = false,
["sb_591650186_1815"] = false,
["sb_497740510_6901"] = false,
},
["preyBarY"] = 167,
["bagPanelSize"] = {
604.999755859375,
632.9999389648438,
},
["expBarX"] = 21,
["repBarBgG"] = 0,
["petReminderSize"] = 18,
["uiFadeNameplates"] = 100,
["repBarFillG"] = 0.2,
["petReminderY"] = 292,
["expBarRestedB"] = 0.8,
["raidFrames"] = {
["aggroG"] = 0.15,
["hotIconSize"] = 14,
["otX"] = -300,
["otGrowDown"] = true,
["aggroEnabled"] = false,
["aggroThreshold"] = 90,
["aggroR"] = 1,
["hotEnabled"] = false,
["otDebuffId"] = 0,
["hotSpells"] = {
},
["otEnabled"] = false,
["otWidth"] = 220,
["otY"] = 200,
["otRowHeight"] = 36,
["aggroB"] = 0.15,
},
["debugEnabled"] = false,
["alsLoadoutEquip"] = {
["57968457"] = {
["equipSetID"] = 5,
["equipSetName"] = "Healer PVP",
},
["59766940"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
["58722257"] = {
["equipSetID"] = 0,
["equipSetName"] = "healer",
},
["57972284"] = {
["equipSetID"] = 4,
["equipSetName"] = "tank pvp",
},
["58908947"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
["57528106"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
["59581023"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
["59580984"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
["59638728"] = {
["equipSetID"] = 2,
["equipSetName"] = "tank raid",
},
},
["specProfiles"] = {
["WARLOCK_266"] = {
["resourceBars"] = {
{
["bgR"] = 0.1,
["label"] = "Soul Shards",
["pipGap"] = 4,
["g"] = 1,
["isPip"] = true,
["showValue"] = false,
["h"] = 47,
["bgB"] = 0.1,
["pipSize"] = 40,
["enabled"] = true,
["r"] = 0.5215686559677124,
["isBar"] = false,
["w"] = 222,
["maxPips"] = 5,
["y"] = -137,
["x"] = -54,
["pipShape"] = "rune",
["bgG"] = 0.1,
["powerType"] = 7,
["unit"] = "player",
["showLabel"] = false,
["b"] = 0.458823561668396,
},
{
["bgR"] = 0.1,
["label"] = "Imps",
["pipGap"] = 4,
["g"] = 1,
["isPip"] = false,
["showValue"] = true,
["h"] = 20,
["bgB"] = 0.1,
["pipSize"] = 18,
["enabled"] = true,
["r"] = 0.2470588386058807,
["isBar"] = true,
["w"] = 200,
["maxPips"] = 5,
["y"] = -268,
["x"] = -35,
["pipShape"] = "square",
["bgG"] = 0.1,
["powerType"] = 22,
["unit"] = "player",
["showLabel"] = true,
["b"] = 0.321568638086319,
},
},
["buffDebuffAlertsEnabled"] = true,
["trackedDebuffs"] = {
},
["trackedBuffs"] = {
},
["trackedExternals"] = {
},
},
["SHAMAN_264"] = {
},
["global"] = {
["buffDebuffAlertsEnabled"] = true,
["trackedBuffs"] = {
{
["alertDuration"] = 0,
["alertX"] = 0,
["alertY"] = 0,
["alertTexture"] = "136090",
["alertSize"] = 64,
["alertBarWidth"] = 200,
["spellId"] = 57723,
["enabled"] = false,
["glowEnabled"] = true,
["hideNativeIcon"] = false,
["alertMode"] = "icon",
["sound"] = "Interface/AddOns/MidnightQoL/Sounds/Pedro.ogg",
["soundIsID"] = true,
},
},
["resourceBars"] = {
{
["bgR"] = 0.1,
["threshSoundIsID"] = false,
["staggerHighR"] = 1,
["label"] = "",
["pipGap"] = 4,
["g"] = 1,
["isPip"] = false,
["showValue"] = false,
["threshEnabled"] = true,
["bgB"] = 0.1,
["pipSize"] = 40,
["maxPips"] = 0,
["unit"] = "player",
["threshSound"] = "Interface/AddOns/MidnightQoL/Sounds/Warning Siren.ogg",
["showLabel"] = false,
["b"] = 0.06666667014360428,
["r"] = 0.2235294282436371,
["threshValue"] = 80,
["isBar"] = true,
["w"] = 400,
["powerType"] = 20,
["y"] = -169,
["x"] = -41,
["pipShape"] = "rune",
["bgG"] = 0.1,
["staggerHighG"] = 0.3,
["staggerHighB"] = 0,
["enabled"] = true,
["h"] = 20,
},
},
},
["MONK_268"] = {
["trackedExternals"] = {
},
["unitFrames"] = {
["targetW"] = 200,
["focusY"] = -280,
["showPlayer"] = true,
["showParty"] = true,
["showTarget"] = true,
["aggroG"] = 0.1,
["playerW"] = 200,
["partyH"] = 44,
["raidH"] = 36,
["petW"] = 120,
["petH"] = 30,
["showHP"] = true,
["enabled"] = true,
["nameFont"] = 11,
["raidSpacingX"] = 2,
["absorbB"] = 1,
["raidX"] = -420,
["petX"] = -300,
["playerH"] = 50,
["absorbG"] = 0.6,
["focusW"] = 180,
["corners"] = {
["TOPLEFT"] = {
["showDur"] = true,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["TOPRIGHT"] = {
["showDur"] = true,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["BOTTOMLEFT"] = {
["showDur"] = false,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
["BOTTOMRIGHT"] = {
["showDur"] = false,
["spells"] = {
0,
0,
0,
},
["showStack"] = true,
["size"] = 14,
},
},
["showPet"] = true,
["borderG"] = 0.15,
["partyW"] = 180,
["raidW"] = 80,
["raidY"] = 160,
["aggroB"] = 0.1,
["incomingG"] = 0.9,
["showHPPct"] = true,
["absorbR"] = 0.2,
["bgAlpha"] = 0.85,
["petY"] = -240,
["raidCols"] = 5,
["partySpacingY"] = 4,
["focusX"] = -300,
["borderB"] = 0.15,
["powerH"] = 4,
["borderR"] = 0.15,
["partyY"] = 160,
["hpFont"] = 10,
["partyX"] = -420,
["borderSize"] = 1,
["targetH"] = 50,
["classColorHP"] = true,
["playerX"] = -300,
["showFocus"] = true,
["targetX"] = 300,
["aggroR"] = 1,
["incomingR"] = 0.2,
["showAbsorb"] = true,
["showIncoming"] = true,
["aggroEnabled"] = true,
["showName"] = true,
["playerY"] = -180,
["raidSpacingY"] = 2,
["targetY"] = -180,
["incomingB"] = 0.2,
["showRaid"] = true,
["focusH"] = 40,
},
["buffDebuffAlertsEnabled"] = true,
["trackedBuffs"] = {
},
["tauntSwapEnabled"] = true,
["trackedTauntDebuffs"] = {
},
["trackedDebuffs"] = {
},
["raidFrames"] = {
["aggroG"] = 0.15,
["hotIconSize"] = 14,
["otX"] = -300,
["otGrowDown"] = true,
["aggroEnabled"] = false,
["aggroThreshold"] = 90,
["aggroR"] = 1,
["hotEnabled"] = false,
["otDebuffId"] = 0,
["hotSpells"] = {
},
["otEnabled"] = false,
["otWidth"] = 220,
["otY"] = 200,
["otRowHeight"] = 36,
["aggroB"] = 0.15,
},
["resourceBars"] = {
{
["bgR"] = 0.1,
["threshSoundIsID"] = false,
["staggerHighR"] = 1,
["label"] = "",
["pipGap"] = 4,
["g"] = 0.6,
["unit"] = "player",
["showValue"] = true,
["threshEnabled"] = false,
["bgB"] = 0.1,
["pipSize"] = 18,
["staggerHighB"] = 0,
["enabled"] = true,
["staggerHighG"] = 0.3,
["h"] = 31,
["r"] = 0.2,
["w"] = 610,
["isBar"] = true,
["threshValue"] = 5,
["x"] = -38,
["y"] = -266,
["powerType"] = 20,
["pipShape"] = "circle",
["bgG"] = 0.1,
["b"] = 1,
["maxPips"] = 5,
["showLabel"] = true,
["isPip"] = false,
},
{
["bgR"] = 0.1,
["threshSoundIsID"] = false,
["staggerHighR"] = 1,
["label"] = "",
["pipGap"] = 4,
["g"] = 0.6000000238418579,
["unit"] = "role:HEALER",
["showValue"] = true,
["threshEnabled"] = false,
["bgB"] = 0.1,
["pipSize"] = 18,
["staggerHighB"] = 0,
["enabled"] = true,
["staggerHighG"] = 0.3,
["h"] = 20,
["r"] = 0.2000000178813934,
["w"] = 200,
["isBar"] = true,
["threshValue"] = 5,
["x"] = 797,
["y"] = -39,
["powerType"] = 0,
["pipShape"] = "square",
["bgG"] = 0.1,
["b"] = 1,
["maxPips"] = 5,
["showLabel"] = true,
["isPip"] = false,
},
},
},
["DRUID_105"] = {
},
["SHAMAN_263"] = {
["trackedExternals"] = {
},
["buffDebuffAlertsEnabled"] = true,
["trackedDebuffs"] = {
},
["trackedBuffs"] = {
},
["resourceBars"] = {
{
["bgR"] = 0.1,
["b"] = 1,
["pipGap"] = 4,
["g"] = 0.6,
["isPip"] = true,
["showValue"] = true,
["h"] = 20,
["bgB"] = 0.1,
["pipSize"] = 18,
["enabled"] = true,
["r"] = 0.2,
["isBar"] = false,
["w"] = 200,
["label"] = "",
["y"] = 328,
["x"] = -40,
["pipShape"] = "thin",
["bgG"] = 0.1,
["showLabel"] = true,
["unit"] = "player",
["powerType"] = 21,
["maxPips"] = 10,
},
},
},
["WARLOCK_265"] = {
["buffDebuffAlertsEnabled"] = true,
["resourceBars"] = {
},
["trackedBuffs"] = {
},
},
["MONK_270"] = {
["resourceBars"] = {
{
["bgR"] = 0.1,
["threshSoundIsID"] = false,
["staggerHighR"] = 1,
["label"] = "Mana",
["pipGap"] = 4,
["g"] = 0.6,
["maxPips"] = 5,
["showValue"] = true,
["h"] = 28,
["bgB"] = 0.1,
["pipSize"] = 18,
["unit"] = "player",
["staggerHighB"] = 0,
["showLabel"] = true,
["isPip"] = false,
["r"] = 0.2,
["b"] = 1,
["isBar"] = true,
["w"] = 761,
["powerType"] = 0,
["y"] = -289,
["x"] = 14,
["pipShape"] = "square",
["bgG"] = 0.1,
["threshValue"] = 5,
["threshEnabled"] = false,
["staggerHighG"] = 0.3,
["enabled"] = true,
},
},
["tauntSwapEnabled"] = true,
["trackedTauntDebuffs"] = {
},
["trackedExternals"] = {
{
["enabled"] = true,
["alertX"] = -379,
["alertY"] = 360,
["alertTexture"] = "Interface\\Icons\\Spell_Nature_Bloodlust",
["glowEnabled"] = true,
["alertSize"] = 64,
["spellId"] = 0,
["alertDuration"] = 0,
["stackCount"] = 0,
["hideNativeIcon"] = true,
["sound"] = "Interface/AddOns/MidnightQoL/Sounds/Knife Throw.ogg",
["soundIsID"] = true,
},
},
["trackedDebuffs"] = {
},
["trackedBuffs"] = {
},
["buffDebuffAlertsEnabled"] = true,
},
},
["expBarColorG"] = 0.6,
["repBarWidth"] = 600,
["dbVersion"] = "2.2.0",
["repBarBgA"] = 0.55,
["breakBarY"] = 90,
["bagPanelPos"] = {
654.500732421875,
-224.4994812011719,
},
["breakBarR"] = 0.2,
["expBarHeight"] = 24,
["breakBarX"] = 752,
["alsLayoutRules"] = {
["3"] = {
["loadoutID"] = 57760643,
["pvpAutoApply"] = false,
["loadoutName"] = "M+",
},
},
["alsLayoutTalents"] = {
["3"] = {
["57760643"] = "M+",
},
},
["resourceBarsEnabled"] = true,
["subBagHideWarbound"] = false,
["repBarShowText"] = true,
["raidbuffCheckEnabled"] = true,
["subBagShowBoundOnly"] = false,
["repBarX"] = 25,
["battlerezEnabled"] = true,
["preyBarX"] = 571,
["breakBarB"] = 1,
["repBarY"] = 517,
["repBarBgB"] = 0,
["whisperList"] = {
},
["petReminderB"] = 0,
["petReminderX"] = -41,
["bagUpgradeEnabled"] = true,
["petReminderG"] = 0.4,
["generalWhisperSound"] = "Interface/AddOns/MidnightQoL/Sounds/Chant.ogg",
["expBarPendingR"] = 1,
["poisonAlertEnabled"] = true,
["alsMappings"] = {
},
["mainFramePos"] = {
["y"] = -7.999829769134522,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -35.99895477294922,
},
["uiFadeActionBars"] = 40,
["expBarRepG"] = 0.2,
["subBagPanelEnabled"] = true,
["tauntSwapEnabled"] = true,
["ignoreOutgoingWhispers"] = true,
["brezY"] = 977.9999780654907,
["petReminderSoundIsID"] = false,
["whisperIndicatorEnabled"] = true,
["expBarMouseover"] = true,
["trackedTauntDebuffs"] = {
},
["petReminderSound"] = "Interface/AddOns/MidnightQoL/Sounds/Roar.ogg",
["expBarBgB"] = 0,
["expBarWidth"] = 709,
["raidBuffHUDY"] = 1062.999755859375,
["breakTimerEnabled"] = true,
["generalWhisperSoundIsID"] = false,
["subBagHideSoulbound"] = false,
["expBarHideAtMax"] = true,
["alsEnabled"] = true,
["repBarHeight"] = 10,
["uiFadeUnitFrames"] = 100,
["expBarShowText"] = true,
["expBarRepB"] = 1,
["expBarPendingG"] = 0.85,
["repBarPendingG"] = 0.85,
["expBarRestedG"] = 0,
["expBarRepR"] = 0.8,
["minimapBtnShown"] = true,
["expBarShowRep"] = true,
["subBagIlvlEnabled"] = true,
["pullTimerEnabled"] = true,
["cdMismatchSuppressed"] = false,
["expBarBgG"] = 0,
["expBarColorB"] = 1,
["raidBuffHUDX"] = 1636.000122070313,
["petReminderEnabled"] = true,
["expBarEnabled"] = true,
["trackedDebuffs"] = {
},
["alsLoadoutLayout"] = {
["57760643"] = {
["layoutName"] = "Classic",
["layoutIndex"] = 2,
},
["57837989"] = {
["layoutName"] = "Default",
["layoutIndex"] = 3,
},
},
["expBarPendingB"] = 0,
["expBarRestedR"] = 0.3,
["repBarFillB"] = 1,
["minimapRadius"] = 106.4248719896462,
["alsEquipTalents"] = {
},
["uiFadeMinimap"] = 100,
["sellConfirmEnabled"] = true,
["preyBarEnabled"] = true,
["unreadMailIconPos"] = {
["y"] = 211,
["x"] = -935,
["point"] = "CENTER",
},
["tabsEnabled"] = {
["Layouts"] = true,
},
["expBarShowTTL"] = true,
["autoQuestTurnIn"] = true,
["meterAutoReset"] = true,
["breakBarG"] = 0.6,
["alsDefaultLayout"] = {
["layoutName"] = "Default",
["layoutIndex"] = 3,
},
["expBarY"] = 466,
["expBarBgR"] = 0,
}


CastbarDB = {
["showTimer"] = true,
["showLatency"] = true,
["colorFinished"] = {
1,
1,
0.4,
},
["colorInterrupted"] = {
1,
0.2,
0.2,
},
["finishedFlashDur"] = 0.25,
["showIcon"] = true,
["iconSize"] = 20,
["showGCD"] = true,
["hideBlizzard"] = true,
["enabled"] = true,
["colorEmpowered"] = {
1,
0.6,
0,
},
["colorChanneling"] = {
0.4,
1,
0.4,
},
["showSpellName"] = true,
["showChannelTicks"] = true,
["width"] = 400,
["y"] = -122,
["x"] = -36,
["colorNonInterrupt"] = {
0.6,
0.6,
0.6,
},
["height"] = 20,
["colorBackground"] = {
0,
0,
0,
},
["colorCasting"] = {
0.2,
0.6,
1,
},
["colorGCD"] = {
1,
1,
1,
},
["colorLatency"] = {
0.7,
0.1,
0.1,
},
}
