name: Package and Release

on:
  push:
    branches:
      - main  # Make sure this matches your branch name in GitHub Desktop

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_RELEASE_TYPE: release  # This force-sets the upload to "Release"