package-as: MidnightQoL

# This tells the packager to move these subfolders to the root of the zip
move-folders:
  MidnightQoL: MidnightQoL
  MidnightQoL_BuffAlerts: MidnightQoL_BuffAlerts
  MidnightQoL_QoL: MidnightQoL_QoL
  MidnightQoL_ResourceBars: MidnightQoL_ResourceBars
  MidnightQoL_Whisper: MidnightQoL_Whisper

ignore:
  - .pkgmeta
  - .gitignore
  - .github
  - .git
  - generate_manifests.py
  - generate_manifests.ps1
  - README.md