name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  tag-creation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create New Tag
        id: tag_action
        uses: mathieudutour/github-tag-action@v6.2
        with:
          # CRITICAL: We use the PAT here so GitHub allows it to trigger the next workflow
          github_token: ${{ secrets.PAT_TOKEN }} 
          default_bump: patch
          tag_prefix: v